### ISSUE TITLE
bard cookie not set or invalid [BUG]

### ISSUE THREAD

**Issue by peanutman1116** [Najmul190/Discord-AI-Selfbot#32]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\discord\client.py", line 507, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\hello\Downloads\Discord-AI-Selfbot-main\Discord-AI-Selfbot-main\main.py", line 282, in on_message
    response = bard.get_answer(user_prompt)
               ^^^^
NameError: name 'bard' is not defined

**Comment by Najmul190** [comment]
bro it must be your python at this point

**Comment by peanutman1116** [comment]
> bro it must be your python at this point

What version do you recommend I got it to start but it won't use bard

**Comment by peanutman1116** [comment]
> bro it must be your python at this point

got it to work is there a way to make it chat automatically

**Comment by ivegot0bitches** [comment]
how did u get it to wrok

**Comment by ivegot0bitches** [comment]
work*
sorry for the typo
