### ISSUE TITLE
[REQUEST]I have tried many times but I can't solve this problem. Can anyone give me some advice? Python3.8

### ISSUE THREAD

**Issue by kingsmile07** [Najmul190/Discord-AI-Selfbot#40]
[2024-01-17 10:38:32] [WARNING ] discord.utils: Info API down. Falling back to manual fetching...
Traceback (most recent call last):
  File "F:\OpenSourceProject\Discord-AI-Selfbot\main.py", line 510, in <module>
    bot.run(TOKEN)
  File "F:\OpenSourceProject\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\client.py", line 938, in run
    asyncio.run(runner())
  File "D:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "F:\OpenSourceProject\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\client.py", line 927, in runner
    await self.start(token, reconnect=reconnect)
  File "F:\OpenSourceProject\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\client.py", line 857, in start
    await self.login(token)
  File "F:\OpenSourceProject\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\client.py", line 698, in login
    data = await state.http.static_login(token.strip())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\OpenSourceProject\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\http.py", line 991, in static_login
    await self.startup()
  File "F:\OpenSourceProject\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\http.py", line 562, in startup
    self.super_properties, self.encoded_super_properties = sp, _ = await utils._get_info(session)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\OpenSourceProject\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\utils.py", line 1446, in _get_info
    bn = await _get_build_number(session)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\OpenSourceProject\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\utils.py", line 1474, in _get_build_number
    build_url = 'https://discord.com/assets/' + re.compile(r'assets/+([a-z0-9]+)\.js').findall(login_page)[-2] + '.js'
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
127.0.0.1 - - [17/Jan/2024 10:38:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Jan/2024 10:38:37] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [17/Jan/2024 10:42:38] "GET / HTTP/1.1" 200 -

**Comment by Najmul190** [comment]
https://github.com/Najmul190/Discord-AI-Selfbot/issues/36
