### ISSUE TITLE
[BUG] KeyError: 'choices'

### ISSUE THREAD

**Issue by C0DE4ME** [Najmul190/Discord-AI-Selfbot#44]
think its just an issue with api/cookies, dunno...?
Bard is now Gemini and ChatGPT has had major upgrades, neither seem to work with this now.

ive looked at #41 , #17 , and #36 
didnt help much :(

i get:

Task exception was never retrieved
future: <Task finished name='Task-22' coro=<on_message.<locals>.generate_response_in_thread() done, defined at C:\Users\Me\Discord-AI-Selfbot\main.py:253> exception=KeyError('choices')>
Traceback (most recent call last):
  File "C:\Users\Me\Discord-AI-Selfbot\main.py", line 254, in generate_response_in_thread
    response = await generate_response(prompt, history)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\Discord-AI-Selfbot\main.py", line 87, in generate_response
    choices = response_data["choices"]
              ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'choices'

**Comment by dhstunn** [comment]
Use bard cookie, chatgpt is broken.

**Comment by C0DE4ME** [comment]
> Use bard cookie, chatgpt is broken.

issue is Bard AI is gone, it is Gemini AI now.
followed the same steps to get cookie, but still have issues, any idea?:

https://github.com/Najmul190/Discord-AI-Selfbot?tab=readme-ov-file#step-4-get-your-bard-cookie-value
Step 4: Get your BARD cookie value
Go to [Google's BARD website](https://bard.google.com/)
Click Sign in or Try it
Press Ctrl + Shift + I (If you are on Windows) or Cmd + Opt + I (If you are on a Mac).
Go to the Application tab
Click on Cookies under Storage on the left side
Click on https://bard.google.com under Cookies
Copy the value of __Secure-1PSID and paste it in the .env file under BARD_COOKIE

ty btw
