### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sam5610** [Najmul190/Discord-AI-Selfbot#67]
hi, i get this error when trying to run the selfbot:

Starting bot...
Traceback (most recent call last):
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\aiohttp\connector.py", line 1080, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1148, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1181, in _create_connection_transport
    await waiter
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python312\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python312\Lib\asyncio\sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 916, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Samuel\Discord-AI-Selfbot\main.py", line 263, in <module>
    asyncio.run(bot.run(token=TOKEN, log_handler=None))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\client.py", line 1106, in run
    asyncio.run(runner())
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\client.py", line 1095, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\client.py", line 1025, in start
    await self.login(token)
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\client.py", line 867, in login
    data = await state.http.static_login(token.strip())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\http.py", line 1058, in static_login
    data = await self.get_me()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\discord\http.py", line 799, in request
    async with self.__session.request(method, url, **kwargs) as response:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\aiohttp\client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\aiohttp\connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\aiohttp\connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\aiohttp\connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Discord-AI-Selfbot\bot-env\Lib\site-packages\aiohttp\connector.py", line 1082, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]
(bot-env) C:\Users\Samuel\Discord-AI-Selfbot>

**Comment by Najmul190** [comment]
This error has nothing to do with the code and seems to be more of a Python installation fault. Only ways to fix it that I could find is to:

- Make sure your system clock is set to the right date and time
- Update Python

I can't help with this further, sorry.
