### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Sxnpaiwin** [Najmul190/Discord-AI-Selfbot#70]
Traceback (most recent call last):
  File "/home/sxnpai/Discord-AI-Selfbot/main.py", line 31, in <module>
    bot.anti_age_ban = os.getenv("ANTI_AGE_BAN").lower()
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by Najmul190** [comment]
did you correctly fill out the `.env` file?

**Comment by Sxnpaiwin** [comment]
yh I did but I fixed it since the example.ev did not have ANTI_AGE_BAN=true so I ran setup.py and fixed its now  but...
Now I got this error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/sxnpai/Discord-AI-Selfbot/main.py", line 263, in <module>
    asyncio.run(bot.run(token=TOKEN, log_handler=None))
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/discord/client.py", line 938, in run
    asyncio.run(runner())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/discord/client.py", line 927, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/discord/client.py", line 857, in start
    await self.login(token)
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/discord/client.py", line 698, in login
    data = await state.http.static_login(token.strip())
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/discord/http.py", line 991, in static_login
    await self.startup()
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/discord/http.py", line 562, in startup
    self.super_properties, self.encoded_super_properties = sp, _ = await utils._get_info(session)
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/discord/utils.py", line 1446, in _get_info
    bn = await _get_build_number(session)
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/discord/utils.py", line 1472, in _get_build_number
    login_page_request = await session.get('https://discord.com/login', timeout=7)
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/aiohttp/connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/sxnpai/Discord-AI-Selfbot/bot-env/lib/python3.10/site-packages/aiohttp/connector.py", line 1088, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Connect call failed ('162.159.135.232', 443)]

**Comment by Najmul190** [comment]
You cropped out the important first half of the error and only showed me the second half

**Comment by Sxnpaiwin** [comment]
nvm I fixed it 
It seems like my host was causing the issue :)
